# all observations, base lin vel, base ang vel, graviy, cmd vel, pos, vel, action
float32 lin_vel_x
float32 lin_vel_y
float32 lin_vel_z

float32 ang_vel_x
float32 ang_vel_y
float32 ang_vel_z

float32 gravity_x
float32 gravity_y
float32 gravity_z

float32 cmd_vel_x
float32 cmd_vel_y
float32 cmd_vel_z

# JOINT POSE
float32 pos_FL_hip
float32 pos_FL_thigh
float32 pos_FL_calf

float32 pos_FR_hip
float32 pos_FR_thigh
float32 pos_FR_calf

float32 pos_RL_hip
float32 pos_RL_thigh
float32 pos_RL_calf

float32 pos_RR_hip
float32 pos_RR_thigh
float32 pos_RR_calf

# JOINT VELOCITY
float32 vel_FL_hip
float32 vel_FL_thigh
float32 vel_FL_calf

float32 vel_FR_hip
float32 vel_FR_thigh
float32 vel_FR_calf

float32 vel_RL_hip
float32 vel_RL_thigh
float32 vel_RL_calf

float32 vel_RR_hip
float32 vel_RR_thigh
float32 vel_RR_calf

# JOINT ACTION
float32 act_FL_hip
float32 act_FL_thigh
float32 act_FL_calf

float32 act_FR_hip
float32 act_FR_thigh
float32 act_FR_calf

float32 act_RL_hip
float32 act_RL_thigh
float32 act_RL_calf

float32 act_RR_hip
float32 act_RR_thigh
float32 act_RR_calf





